// Mock Data for Octomate HR System Demo
// Realistic Singapore employee profiles

import { Employee, AuditLogEntry, User, UserRole } from './types';
import { generateEmployeeId, calculateRetirementYear, calculateRetirementDate } from './validations';

export const NATIONALITIES = [
  'Singaporean',
  'Malaysian',
  'Indonesian',
  'Filipino',
  'Indian',
  'Chinese (PRC)',
  'Vietnamese',
  'Thai',
  'Myanmar',
  'British',
  'American',
  'Australian',
];

export const DEPARTMENTS = [
  'Human Resources',
  'Engineering',
  'Sales',
  'Finance',
  'Marketing',
  'Operations',
  'Customer Success',
  'Product',
  'Legal',
  'Administration',
];

export const BANKS = [
  { code: 'DBS', name: 'DBS Bank', swift: 'DBSSSGSG' },
  { code: 'OCBC', name: 'OCBC Bank', swift: 'OCBCSGSG' },
  { code: 'UOB', name: 'United Overseas Bank', swift: 'UOVBSGSG' },
  { code: 'SCB', name: 'Standard Chartered', swift: 'SCBLSGSG' },
  { code: 'CITI', name: 'Citibank', swift: 'CITISGSG' },
  { code: 'HSBC', name: 'HSBC', swift: 'HSBCSGSG' },
  { code: 'MAYBANK', name: 'Maybank', swift: 'MBBESGSG' },
];

export const mockEmployees: Employee[] = [
  {
    id: '1',
    fullName: 'Tan Wei Ming',
    alias: 'Wei Ming',
    nricFin: 'S8812345D', // Valid NRIC format
    identityNo: 'S8812345D',
    cardType: 'NRIC',
    nationality: 'Singaporean',
    dateOfBirth: '1988-06-15',
    gender: 'Male',
    race: 'Chinese',
    religion: 'Buddhism',
    maritalStatus: 'Married',
    photoUrl: '',
    workEmail: 'weiming.tan@octomate.sg',
    employeeId: 'EMP-2020-0001',
    department: 'Engineering',
    jobTitle: 'Senior Software Engineer',
    employmentDate: '2020-03-15',
    retirementAge: 63,
    retirementYear: calculateRetirementYear('1988-06-15', 63),
    retirementDate: calculateRetirementDate('1988-06-15', 63),
    employmentStatus: 'Active',
    contactNo: '+65 9123 4567',
    homeNo: '+65 6234 5678',
    personalEmail: 'weiming88@gmail.com',
    mailingAddress: {
      addressLine1: 'Blk 123 Toa Payoh Lorong 1',
      addressLine2: '#12-345',
      postalCode: '310123',
    },
    bankingInfo: {
      namePerBankAccount: 'TAN WEI MING',
      bankCountry: 'Singapore',
      bankEntity: 'DBS Bank',
      branchCode: '001',
      accountNumber: '1234567890',
      bicSwiftCode: 'DBSSSGSG',
    },
    highestQualification: 'Bachelors',
    educationHistory: [
      {
        id: 'edu-1',
        institution: 'National University of Singapore',
        qualification: 'Bachelors',
        fieldOfStudy: 'Computer Science',
        yearObtained: 2010,
      },
    ],
    workExperience: [
      {
        id: 'exp-1',
        companyName: 'Tech Solutions Pte Ltd',
        jobTitle: 'Software Engineer',
        startDate: '2010-07-01',
        endDate: '2020-03-01',
        description: 'Full-stack development using Java and React',
        isCurrent: false,
      },
    ],
    emergencyContact1: {
      name: 'Tan Mei Ling',
      mobileNumber: '+65 9234 5678',
      relationship: 'Spouse',
      homeOfficeNumber: '+65 6234 5678',
    },
    emergencyContact2: {
      name: 'Tan Ah Kow',
      mobileNumber: '+65 9345 6789',
      relationship: 'Parent',
    },
    createdAt: '2020-03-15T09:00:00Z',
    updatedAt: '2024-12-20T14:30:00Z',
    pdpaConsent: true,
    pdpaConsentDate: '2020-03-15T09:00:00Z',
  },
  {
    id: '2',
    fullName: 'Priya Sharma',
    alias: 'Priya',
    nricFin: 'G1234567N',
    identityNo: 'G1234567N',
    cardType: 'FIN',
    nationality: 'Indian',
    dateOfBirth: '1992-11-22',
    gender: 'Female',
    race: 'Indian',
    religion: 'Hinduism',
    maritalStatus: 'Single',
    photoUrl: '',
    workEmail: 'priya.sharma@octomate.sg',
    employeeId: 'EMP-2021-0015',
    department: 'Human Resources',
    jobTitle: 'HR Business Partner',
    employmentDate: '2021-08-01',
    retirementAge: 63,
    retirementYear: calculateRetirementYear('1992-11-22', 63),
    retirementDate: calculateRetirementDate('1992-11-22', 63),
    employmentStatus: 'Active',
    contactNo: '+65 8234 5678',
    personalEmail: 'priya.sharma92@gmail.com',
    mailingAddress: {
      addressLine1: '25 Robertson Quay',
      addressLine2: '#08-12 The Pier',
      postalCode: '238236',
    },
    overseasAddress: {
      addressLine: '42 MG Road, Bangalore',
      postalCode: '560001',
      country: 'India',
    },
    bankingInfo: {
      namePerBankAccount: 'PRIYA SHARMA',
      bankCountry: 'Singapore',
      bankEntity: 'OCBC Bank',
      branchCode: '503',
      accountNumber: '5678901234',
      bicSwiftCode: 'OCBCSGSG',
    },
    highestQualification: 'Masters',
    educationHistory: [
      {
        id: 'edu-2',
        institution: 'Delhi University',
        qualification: 'Bachelors',
        fieldOfStudy: 'Psychology',
        yearObtained: 2014,
      },
      {
        id: 'edu-3',
        institution: 'Singapore Management University',
        qualification: 'Masters',
        fieldOfStudy: 'Human Capital Leadership',
        yearObtained: 2020,
      },
    ],
    workExperience: [
      {
        id: 'exp-2',
        companyName: 'Infosys Ltd',
        jobTitle: 'HR Executive',
        startDate: '2014-06-01',
        endDate: '2019-07-31',
        description: 'Talent acquisition and employee relations',
        isCurrent: false,
      },
    ],
    emergencyContact1: {
      name: 'Rajesh Sharma',
      mobileNumber: '+91 98765 43210',
      relationship: 'Parent',
    },
    createdAt: '2021-08-01T09:00:00Z',
    updatedAt: '2024-12-15T11:20:00Z',
    pdpaConsent: true,
    pdpaConsentDate: '2021-08-01T09:00:00Z',
  },
  {
    id: '3',
    fullName: 'Muhammad Faisal bin Abdullah',
    alias: 'Faisal',
    nricFin: 'S9012345B',
    identityNo: 'S9012345B',
    cardType: 'NRIC',
    nationality: 'Singaporean',
    dateOfBirth: '1990-03-08',
    gender: 'Male',
    race: 'Malay',
    religion: 'Islam',
    maritalStatus: 'Married',
    photoUrl: '',
    workEmail: 'faisal.abdullah@octomate.sg',
    employeeId: 'EMP-2019-0008',
    department: 'Sales',
    jobTitle: 'Sales Director',
    employmentDate: '2019-01-15',
    retirementAge: 63,
    retirementYear: calculateRetirementYear('1990-03-08', 63),
    retirementDate: calculateRetirementDate('1990-03-08', 63),
    employmentStatus: 'Active',
    contactNo: '+65 9345 6789',
    homeNo: '+65 6345 6789',
    personalEmail: 'faisal.abdullah@yahoo.com',
    mailingAddress: {
      addressLine1: 'Blk 456 Tampines Street 42',
      addressLine2: '#05-678',
      postalCode: '520456',
    },
    bankingInfo: {
      namePerBankAccount: 'MUHAMMAD FAISAL BIN ABDULLAH',
      bankCountry: 'Singapore',
      bankEntity: 'Maybank',
      branchCode: '001',
      accountNumber: '0987654321',
      bicSwiftCode: 'MBBESGSG',
    },
    highestQualification: 'Bachelors',
    educationHistory: [
      {
        id: 'edu-4',
        institution: 'Nanyang Technological University',
        qualification: 'Bachelors',
        fieldOfStudy: 'Business Administration',
        yearObtained: 2012,
      },
    ],
    workExperience: [
      {
        id: 'exp-3',
        companyName: 'Singtel',
        jobTitle: 'Account Manager',
        startDate: '2012-07-01',
        endDate: '2019-01-14',
        description: 'B2B sales and account management',
        isCurrent: false,
      },
    ],
    emergencyContact1: {
      name: 'Siti Aminah bte Hassan',
      mobileNumber: '+65 9456 7890',
      relationship: 'Spouse',
      homeOfficeNumber: '+65 6345 6789',
    },
    createdAt: '2019-01-15T09:00:00Z',
    updatedAt: '2024-12-18T16:45:00Z',
    pdpaConsent: true,
    pdpaConsentDate: '2019-01-15T09:00:00Z',
  },
  {
    id: '4',
    fullName: 'Sarah Lim Hui Wen',
    alias: 'Sarah',
    nricFin: 'T0512345C',
    identityNo: 'T0512345C',
    cardType: 'NRIC',
    nationality: 'Singaporean',
    dateOfBirth: '2005-09-12',
    gender: 'Female',
    race: 'Chinese',
    religion: 'Christianity',
    maritalStatus: 'Single',
    photoUrl: '',
    workEmail: 'sarah.lim@octomate.sg',
    employeeId: 'EMP-2024-0042',
    department: 'Marketing',
    jobTitle: 'Marketing Intern',
    employmentDate: '2024-06-01',
    retirementAge: 63,
    retirementYear: calculateRetirementYear('2005-09-12', 63),
    retirementDate: calculateRetirementDate('2005-09-12', 63),
    employmentStatus: 'Probation',
    contactNo: '+65 8456 7890',
    personalEmail: 'sarahlim2005@gmail.com',
    mailingAddress: {
      addressLine1: '88 Bukit Timah Road',
      addressLine2: '#15-02 Prestige Heights',
      postalCode: '229832',
    },
    bankingInfo: {
      namePerBankAccount: 'SARAH LIM HUI WEN',
      bankCountry: 'Singapore',
      bankEntity: 'DBS Bank',
      branchCode: '012',
      accountNumber: '1122334455',
      bicSwiftCode: 'DBSSSGSG',
    },
    highestQualification: 'A-Level',
    educationHistory: [
      {
        id: 'edu-5',
        institution: 'Raffles Junior College',
        qualification: 'A-Level',
        fieldOfStudy: 'Arts Stream',
        yearObtained: 2023,
      },
    ],
    workExperience: [],
    emergencyContact1: {
      name: 'Lim Keng Huat',
      mobileNumber: '+65 9567 8901',
      relationship: 'Parent',
      homeOfficeNumber: '+65 6789 0123',
    },
    emergencyContact2: {
      name: 'Jennifer Lim',
      mobileNumber: '+65 9678 9012',
      relationship: 'Parent',
    },
    createdAt: '2024-06-01T09:00:00Z',
    updatedAt: '2024-12-22T09:15:00Z',
    pdpaConsent: true,
    pdpaConsentDate: '2024-06-01T09:00:00Z',
  },
  {
    id: '5',
    fullName: 'Nguyen Thi Mai',
    alias: 'Mai',
    nricFin: 'F9876543P',
    identityNo: 'F9876543P',
    cardType: 'FIN',
    nationality: 'Vietnamese',
    dateOfBirth: '1995-01-28',
    gender: 'Female',
    race: 'Others',
    religion: 'Buddhism',
    maritalStatus: 'Single',
    photoUrl: '',
    workEmail: 'mai.nguyen@octomate.sg',
    employeeId: 'EMP-2022-0023',
    department: 'Finance',
    jobTitle: 'Financial Analyst',
    employmentDate: '2022-04-18',
    retirementAge: 63,
    retirementYear: calculateRetirementYear('1995-01-28', 63),
    retirementDate: calculateRetirementDate('1995-01-28', 63),
    employmentStatus: 'Active',
    contactNo: '+65 8567 8901',
    personalEmail: 'nguyen.mai95@gmail.com',
    mailingAddress: {
      addressLine1: '5 Cantonment Road',
      addressLine2: '#22-08 Pinnacle@Duxton',
      postalCode: '080005',
    },
    overseasAddress: {
      addressLine: '123 Le Loi Street, District 1, Ho Chi Minh City',
      postalCode: '700000',
      country: 'Vietnam',
    },
    bankingInfo: {
      namePerBankAccount: 'NGUYEN THI MAI',
      bankCountry: 'Singapore',
      bankEntity: 'United Overseas Bank',
      branchCode: '001',
      accountNumber: '6677889900',
      bicSwiftCode: 'UOVBSGSG',
    },
    highestQualification: 'Bachelors',
    educationHistory: [
      {
        id: 'edu-6',
        institution: 'Ho Chi Minh City University of Economics',
        qualification: 'Bachelors',
        fieldOfStudy: 'Finance',
        yearObtained: 2017,
      },
    ],
    workExperience: [
      {
        id: 'exp-4',
        companyName: 'Deloitte Vietnam',
        jobTitle: 'Audit Associate',
        startDate: '2017-09-01',
        endDate: '2022-03-31',
        description: 'External audit for financial services clients',
        isCurrent: false,
      },
    ],
    emergencyContact1: {
      name: 'Nguyen Van Hoa',
      mobileNumber: '+84 912 345 678',
      relationship: 'Parent',
    },
    createdAt: '2022-04-18T09:00:00Z',
    updatedAt: '2024-12-19T13:00:00Z',
    pdpaConsent: true,
    pdpaConsentDate: '2022-04-18T09:00:00Z',
  },
  {
    id: '6',
    fullName: 'David Wong Chee Keong',
    alias: 'David',
    nricFin: 'S7512345D',
    identityNo: 'S7512345D',
    cardType: 'NRIC',
    nationality: 'Singaporean',
    dateOfBirth: '1975-12-05',
    gender: 'Male',
    race: 'Chinese',
    religion: 'Taoism',
    maritalStatus: 'Married',
    photoUrl: '',
    workEmail: 'david.wong@octomate.sg',
    employeeId: 'EMP-2015-0003',
    department: 'Operations',
    jobTitle: 'Chief Operating Officer',
    employmentDate: '2015-06-01',
    retirementAge: 63,
    retirementYear: calculateRetirementYear('1975-12-05', 63),
    retirementDate: calculateRetirementDate('1975-12-05', 63),
    employmentStatus: 'Active',
    contactNo: '+65 9678 9012',
    homeNo: '+65 6456 7890',
    personalEmail: 'davidwong75@hotmail.com',
    mailingAddress: {
      addressLine1: '18 Nassim Road',
      addressLine2: '',
      postalCode: '258372',
    },
    bankingInfo: {
      namePerBankAccount: 'DAVID WONG CHEE KEONG',
      bankCountry: 'Singapore',
      bankEntity: 'HSBC',
      branchCode: '001',
      accountNumber: '2233445566',
      bicSwiftCode: 'HSBCSGSG',
    },
    highestQualification: 'Masters',
    educationHistory: [
      {
        id: 'edu-7',
        institution: 'National University of Singapore',
        qualification: 'Bachelors',
        fieldOfStudy: 'Economics',
        yearObtained: 1997,
      },
      {
        id: 'edu-8',
        institution: 'INSEAD',
        qualification: 'Masters',
        fieldOfStudy: 'MBA',
        yearObtained: 2005,
      },
    ],
    workExperience: [
      {
        id: 'exp-5',
        companyName: 'McKinsey & Company',
        jobTitle: 'Senior Consultant',
        startDate: '2005-09-01',
        endDate: '2015-05-31',
        description: 'Strategy consulting for Fortune 500 clients',
        isCurrent: false,
      },
    ],
    emergencyContact1: {
      name: 'Grace Wong',
      mobileNumber: '+65 9789 0123',
      relationship: 'Spouse',
      homeOfficeNumber: '+65 6456 7890',
    },
    createdAt: '2015-06-01T09:00:00Z',
    updatedAt: '2024-12-21T10:30:00Z',
    pdpaConsent: true,
    pdpaConsentDate: '2015-06-01T09:00:00Z',
  },
  {
    id: '7',
    fullName: 'Ahmad bin Osman',
    alias: 'Ahmad',
    nricFin: 'S8212345E',
    identityNo: 'S8212345E',
    cardType: 'NRIC',
    nationality: 'Singaporean',
    dateOfBirth: '1982-07-20',
    gender: 'Male',
    race: 'Malay',
    religion: 'Islam',
    maritalStatus: 'Married',
    photoUrl: '',
    workEmail: 'ahmad.osman@octomate.sg',
    employeeId: 'EMP-2018-0012',
    department: 'Customer Success',
    jobTitle: 'Customer Success Manager',
    employmentDate: '2018-09-01',
    retirementAge: 63,
    retirementYear: calculateRetirementYear('1982-07-20', 63),
    retirementDate: calculateRetirementDate('1982-07-20', 63),
    employmentStatus: 'Active',
    contactNo: '+65 9890 1234',
    personalEmail: 'ahmad.osman82@gmail.com',
    mailingAddress: {
      addressLine1: 'Blk 789 Yishun Ring Road',
      addressLine2: '#03-456',
      postalCode: '760789',
    },
    bankingInfo: {
      namePerBankAccount: 'AHMAD BIN OSMAN',
      bankCountry: 'Singapore',
      bankEntity: 'DBS Bank',
      branchCode: '003',
      accountNumber: '7788990011',
      bicSwiftCode: 'DBSSSGSG',
    },
    highestQualification: 'Diploma',
    educationHistory: [
      {
        id: 'edu-9',
        institution: 'Singapore Polytechnic',
        qualification: 'Diploma',
        fieldOfStudy: 'Business Information Technology',
        yearObtained: 2003,
      },
    ],
    workExperience: [
      {
        id: 'exp-6',
        companyName: 'StarHub',
        jobTitle: 'Customer Service Team Lead',
        startDate: '2003-07-01',
        endDate: '2018-08-31',
        description: 'Leading customer service operations',
        isCurrent: false,
      },
    ],
    emergencyContact1: {
      name: 'Fatimah bte Yusof',
      mobileNumber: '+65 9901 2345',
      relationship: 'Spouse',
    },
    createdAt: '2018-09-01T09:00:00Z',
    updatedAt: '2024-12-17T15:20:00Z',
    pdpaConsent: true,
    pdpaConsentDate: '2018-09-01T09:00:00Z',
  },
  {
    id: '8',
    fullName: 'Chen Mei Ling',
    alias: 'Mei Ling',
    nricFin: 'S8612345F',
    identityNo: 'S8612345F',
    cardType: 'NRIC',
    nationality: 'Singaporean',
    dateOfBirth: '1986-04-18',
    gender: 'Female',
    race: 'Chinese',
    religion: 'No Religion',
    maritalStatus: 'Divorced',
    photoUrl: '',
    workEmail: 'meiling.chen@octomate.sg',
    employeeId: 'EMP-2017-0007',
    department: 'Product',
    jobTitle: 'Product Manager',
    employmentDate: '2017-02-20',
    retirementAge: 63,
    retirementYear: calculateRetirementYear('1986-04-18', 63),
    retirementDate: calculateRetirementDate('1986-04-18', 63),
    employmentStatus: 'On Leave',
    contactNo: '+65 8012 3456',
    personalEmail: 'meilingchen86@gmail.com',
    mailingAddress: {
      addressLine1: '100 Orchard Road',
      addressLine2: '#20-05 The Orchard Residences',
      postalCode: '238840',
    },
    bankingInfo: {
      namePerBankAccount: 'CHEN MEI LING',
      bankCountry: 'Singapore',
      bankEntity: 'OCBC Bank',
      branchCode: '501',
      accountNumber: '8899001122',
      bicSwiftCode: 'OCBCSGSG',
    },
    highestQualification: 'Masters',
    educationHistory: [
      {
        id: 'edu-10',
        institution: 'National University of Singapore',
        qualification: 'Bachelors',
        fieldOfStudy: 'Information Systems',
        yearObtained: 2008,
      },
      {
        id: 'edu-11',
        institution: 'Stanford University',
        qualification: 'Masters',
        fieldOfStudy: 'Computer Science',
        yearObtained: 2012,
      },
    ],
    workExperience: [
      {
        id: 'exp-7',
        companyName: 'Google Singapore',
        jobTitle: 'Associate Product Manager',
        startDate: '2012-09-01',
        endDate: '2017-02-15',
        description: 'Product management for Google Maps features',
        isCurrent: false,
      },
    ],
    emergencyContact1: {
      name: 'Chen Ah Huat',
      mobileNumber: '+65 9123 4567',
      relationship: 'Parent',
    },
    createdAt: '2017-02-20T09:00:00Z',
    updatedAt: '2024-12-16T08:45:00Z',
    pdpaConsent: true,
    pdpaConsentDate: '2017-02-20T09:00:00Z',
  },
  {
    id: '9',
    fullName: 'Raj Kumar',
    alias: 'Raj',
    nricFin: 'S7912345G',
    identityNo: 'S7912345G',
    cardType: 'NRIC',
    nationality: 'Singaporean',
    dateOfBirth: '1979-10-30',
    gender: 'Male',
    race: 'Indian',
    religion: 'Hinduism',
    maritalStatus: 'Married',
    photoUrl: '',
    workEmail: 'raj.kumar@octomate.sg',
    employeeId: 'EMP-2016-0005',
    department: 'Legal',
    jobTitle: 'Legal Counsel',
    employmentDate: '2016-11-01',
    retirementAge: 63,
    retirementYear: calculateRetirementYear('1979-10-30', 63),
    retirementDate: calculateRetirementDate('1979-10-30', 63),
    employmentStatus: 'Active',
    contactNo: '+65 9234 5678',
    homeNo: '+65 6567 8901',
    personalEmail: 'rajkumar79@gmail.com',
    mailingAddress: {
      addressLine1: '15 Serangoon North Avenue 5',
      addressLine2: '#08-123 Serangoon Ville',
      postalCode: '554915',
    },
    bankingInfo: {
      namePerBankAccount: 'RAJ KUMAR',
      bankCountry: 'Singapore',
      bankEntity: 'Standard Chartered',
      branchCode: '001',
      accountNumber: '9900112233',
      bicSwiftCode: 'SCBLSGSG',
    },
    highestQualification: 'Masters',
    educationHistory: [
      {
        id: 'edu-12',
        institution: 'National University of Singapore',
        qualification: 'Bachelors',
        fieldOfStudy: 'Law',
        yearObtained: 2002,
      },
      {
        id: 'edu-13',
        institution: 'Harvard Law School',
        qualification: 'Masters',
        fieldOfStudy: 'Corporate Law',
        yearObtained: 2008,
      },
    ],
    workExperience: [
      {
        id: 'exp-8',
        companyName: 'Allen & Gledhill',
        jobTitle: 'Senior Associate',
        startDate: '2008-09-01',
        endDate: '2016-10-31',
        description: 'Corporate M&A and regulatory compliance',
        isCurrent: false,
      },
    ],
    emergencyContact1: {
      name: 'Lakshmi Kumar',
      mobileNumber: '+65 9345 6789',
      relationship: 'Spouse',
      homeOfficeNumber: '+65 6567 8901',
    },
    createdAt: '2016-11-01T09:00:00Z',
    updatedAt: '2024-12-20T17:00:00Z',
    pdpaConsent: true,
    pdpaConsentDate: '2016-11-01T09:00:00Z',
  },
  {
    id: '10',
    fullName: 'Lee Jia Hui',
    alias: '',
    nricFin: 'S6512345H',
    identityNo: 'S6512345H',
    cardType: 'NRIC',
    nationality: 'Singaporean',
    dateOfBirth: '1965-02-14',
    gender: 'Male',
    race: 'Chinese',
    religion: 'Buddhism',
    maritalStatus: 'Widowed',
    photoUrl: '',
    workEmail: 'jiahui.lee@octomate.sg',
    employeeId: 'EMP-2010-0001',
    department: 'Administration',
    jobTitle: 'Office Manager',
    employmentDate: '2010-01-04',
    retirementAge: 63,
    retirementYear: calculateRetirementYear('1965-02-14', 63),
    retirementDate: calculateRetirementDate('1965-02-14', 63),
    reEmploymentDate: '2028-02-15',
    employmentStatus: 'Active',
    contactNo: '+65 9456 7890',
    homeNo: '+65 6678 9012',
    personalEmail: 'leejiahui65@yahoo.com.sg',
    mailingAddress: {
      addressLine1: 'Blk 234 Ang Mo Kio Avenue 3',
      addressLine2: '#04-567',
      postalCode: '560234',
    },
    bankingInfo: {
      namePerBankAccount: 'LEE JIA HUI',
      bankCountry: 'Singapore',
      bankEntity: 'OCBC Bank',
      branchCode: '502',
      accountNumber: '1100223344',
      bicSwiftCode: 'OCBCSGSG',
    },
    highestQualification: 'O-Level',
    educationHistory: [
      {
        id: 'edu-14',
        institution: 'Ang Mo Kio Secondary School',
        qualification: 'O-Level',
        fieldOfStudy: 'General Education',
        yearObtained: 1981,
      },
    ],
    workExperience: [
      {
        id: 'exp-9',
        companyName: 'Singapore Press Holdings',
        jobTitle: 'Administrative Executive',
        startDate: '1985-01-01',
        endDate: '2009-12-31',
        description: 'Office administration and facilities management',
        isCurrent: false,
      },
    ],
    emergencyContact1: {
      name: 'Lee Wei Jie',
      mobileNumber: '+65 9567 8901',
      relationship: 'Child',
    },
    createdAt: '2010-01-04T09:00:00Z',
    updatedAt: '2024-12-14T11:00:00Z',
    pdpaConsent: true,
    pdpaConsentDate: '2010-01-04T09:00:00Z',
  },
];

export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: 'audit-1',
    employeeId: '1',
    employeeName: 'Tan Wei Ming',
    timestamp: '2024-12-20T14:30:00Z',
    userId: 'user-1',
    userName: 'Priya Sharma',
    userRole: 'hr_admin',
    action: 'update',
    field: 'contactNo',
    oldValue: '+65 9123 4560',
    newValue: '+65 9123 4567',
    description: 'Updated contact number',
  },
  {
    id: 'audit-2',
    employeeId: '4',
    employeeName: 'Sarah Lim Hui Wen',
    timestamp: '2024-12-22T09:15:00Z',
    userId: 'user-1',
    userName: 'Priya Sharma',
    userRole: 'hr_admin',
    action: 'create',
    description: 'Created new employee profile',
  },
  {
    id: 'audit-3',
    employeeId: '8',
    employeeName: 'Chen Mei Ling',
    timestamp: '2024-12-16T08:45:00Z',
    userId: 'user-1',
    userName: 'Priya Sharma',
    userRole: 'hr_admin',
    action: 'update',
    field: 'employmentStatus',
    oldValue: 'Active',
    newValue: 'On Leave',
    description: 'Updated employment status to On Leave',
  },
  {
    id: 'audit-4',
    employeeId: '3',
    employeeName: 'Muhammad Faisal bin Abdullah',
    timestamp: '2024-12-18T16:45:00Z',
    userId: 'user-3',
    userName: 'Muhammad Faisal bin Abdullah',
    userRole: 'employee',
    action: 'update',
    field: 'emergencyContact1',
    oldValue: '{"name": "Siti Aminah", "mobileNumber": "+65 9456 7800"}',
    newValue: '{"name": "Siti Aminah bte Hassan", "mobileNumber": "+65 9456 7890"}',
    description: 'Updated emergency contact information',
  },
  {
    id: 'audit-5',
    employeeId: '6',
    employeeName: 'David Wong Chee Keong',
    timestamp: '2024-12-21T10:30:00Z',
    userId: 'user-1',
    userName: 'Priya Sharma',
    userRole: 'hr_admin',
    action: 'view',
    description: 'Viewed employee profile',
  },
  {
    id: 'audit-6',
    employeeId: '2',
    employeeName: 'Priya Sharma',
    timestamp: '2024-12-15T11:20:00Z',
    userId: 'user-2',
    userName: 'Priya Sharma',
    userRole: 'employee',
    action: 'update',
    field: 'mailingAddress',
    oldValue: '{"addressLine1": "20 Robertson Quay", "postalCode": "238236"}',
    newValue: '{"addressLine1": "25 Robertson Quay", "addressLine2": "#08-12 The Pier", "postalCode": "238236"}',
    description: 'Updated mailing address',
  },
  {
    id: 'audit-7',
    employeeId: '5',
    employeeName: 'Nguyen Thi Mai',
    timestamp: '2024-12-19T13:00:00Z',
    userId: 'user-1',
    userName: 'Priya Sharma',
    userRole: 'hr_admin',
    action: 'update',
    field: 'bankingInfo',
    oldValue: '{"accountNumber": "****9900"}',
    newValue: '{"accountNumber": "****8900"}',
    description: 'Updated banking information',
  },
  {
    id: 'audit-8',
    employeeId: '7',
    employeeName: 'Ahmad bin Osman',
    timestamp: '2024-12-17T15:20:00Z',
    userId: 'user-1',
    userName: 'Priya Sharma',
    userRole: 'hr_admin',
    action: 'export',
    description: 'Exported employee data',
  },
];

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Priya Sharma',
    email: 'priya.sharma@octomate.sg',
    role: 'hr_admin',
    employeeId: '2',
    avatar: '',
  },
  {
    id: 'user-2',
    name: 'David Wong',
    email: 'david.wong@octomate.sg',
    role: 'manager',
    employeeId: '6',
    avatar: '',
  },
  {
    id: 'user-3',
    name: 'Tan Wei Ming',
    email: 'weiming.tan@octomate.sg',
    role: 'employee',
    employeeId: '1',
    avatar: '',
  },
];

export function getDefaultUser(): User {
  return mockUsers[0]; // HR Admin by default
}

export function getUserByRole(role: UserRole): User {
  return mockUsers.find(u => u.role === role) || mockUsers[0];
}

